// ═══════════════════════════════════════════════════════════
// DATA.JS — All static data: cities, body systems, symptoms, presets
// ═══════════════════════════════════════════════════════════

const CITIES = [
  // Asia
  {id:'TKY',name:'Tokyo',country:'Japan',lat:35.68,lng:139.69,pop:37400000,hub:true},
  {id:'DEL',name:'Delhi',country:'India',lat:28.61,lng:77.21,pop:32900000,hub:true},
  {id:'SHA',name:'Shanghai',country:'China',lat:31.23,lng:121.47,pop:28500000,hub:true},
  {id:'DHK',name:'Dhaka',country:'Bangladesh',lat:23.72,lng:90.41,pop:22000000,hub:false},
  {id:'BOM',name:'Mumbai',country:'India',lat:19.08,lng:72.88,pop:21700000,hub:true},
  {id:'BEJ',name:'Beijing',country:'China',lat:39.91,lng:116.39,pop:21500000,hub:true},
  {id:'OSA',name:'Osaka',country:'Japan',lat:34.69,lng:135.50,pop:19059000,hub:false},
  {id:'KAR',name:'Karachi',country:'Pakistan',lat:24.86,lng:67.01,pop:17236000,hub:false},
  {id:'CHN',name:'Chennai',country:'India',lat:13.08,lng:80.27,pop:11503000,hub:false},
  {id:'ISL',name:'Islamabad',country:'Pakistan',lat:33.72,lng:73.04,pop:1095000,hub:false},
  {id:'BKK',name:'Bangkok',country:'Thailand',lat:13.75,lng:100.52,pop:17600000,hub:true},
  {id:'SEO',name:'Seoul',country:'South Korea',lat:37.57,lng:126.98,pop:9963000,hub:true},
  {id:'HKG',name:'Hong Kong',country:'China',lat:22.31,lng:114.17,pop:7482000,hub:true},
  {id:'SIN',name:'Singapore',country:'Singapore',lat:1.35,lng:103.82,pop:5850000,hub:true},
  {id:'KUL',name:'Kuala Lumpur',country:'Malaysia',lat:3.14,lng:101.69,pop:8419000,hub:true},
  {id:'JAK',name:'Jakarta',country:'Indonesia',lat:-6.21,lng:106.85,pop:34540000,hub:true},
  {id:'MNL',name:'Manila',country:'Philippines',lat:14.60,lng:120.98,pop:24100000,hub:false},
  {id:'HAN',name:'Hanoi',country:'Vietnam',lat:21.03,lng:105.85,pop:5600000,hub:false},
  {id:'TPE',name:'Taipei',country:'Taiwan',lat:25.05,lng:121.53,pop:7040000,hub:true},
  {id:'KHI',name:'Kolkata',country:'India',lat:22.57,lng:88.36,pop:15700000,hub:false},
  {id:'CBR',name:'Colombo',country:'Sri Lanka',lat:6.93,lng:79.85,pop:752000,hub:false},
  {id:'TAS',name:'Tashkent',country:'Uzbekistan',lat:41.30,lng:69.24,pop:2600000,hub:false},
  {id:'ALA',name:'Almaty',country:'Kazakhstan',lat:43.24,lng:76.89,pop:2000000,hub:false},
  // Middle East
  {id:'DXB',name:'Dubai',country:'UAE',lat:25.20,lng:55.27,pop:3600000,hub:true},
  {id:'RUH',name:'Riyadh',country:'Saudi Arabia',lat:24.69,lng:46.72,pop:7670000,hub:false},
  {id:'IST',name:'Istanbul',country:'Turkey',lat:41.01,lng:28.95,pop:15840000,hub:true},
  {id:'TEH',name:'Tehran',country:'Iran',lat:35.69,lng:51.42,pop:14000000,hub:false},
  {id:'BAG',name:'Baghdad',country:'Iraq',lat:33.34,lng:44.40,pop:7800000,hub:false},
  {id:'KHR',name:'Karachi',country:'Pakistan',lat:24.86,lng:67.01,pop:16000000,hub:false},
  // Europe
  {id:'LON',name:'London',country:'UK',lat:51.51,lng:-.13,pop:9648000,hub:true},
  {id:'PAR',name:'Paris',country:'France',lat:48.86,lng:2.35,pop:11060000,hub:true},
  {id:'BER',name:'Berlin',country:'Germany',lat:52.52,lng:13.40,pop:3769000,hub:true},
  {id:'MAD',name:'Madrid',country:'Spain',lat:40.42,lng:-3.70,pop:6750000,hub:true},
  {id:'ROM',name:'Rome',country:'Italy',lat:41.90,lng:12.50,pop:4355000,hub:false},
  {id:'MSC',name:'Moscow',country:'Russia',lat:55.75,lng:37.62,pop:12506000,hub:true},
  {id:'AMS',name:'Amsterdam',country:'Netherlands',lat:52.37,lng:4.90,pop:1148000,hub:true},
  {id:'FRK',name:'Frankfurt',country:'Germany',lat:50.11,lng:8.68,pop:760000,hub:true},
  {id:'BCN',name:'Barcelona',country:'Spain',lat:41.39,lng:2.15,pop:5600000,hub:false},
  {id:'MIL',name:'Milan',country:'Italy',lat:45.46,lng:9.19,pop:3250000,hub:false},
  {id:'WAR',name:'Warsaw',country:'Poland',lat:52.23,lng:21.01,pop:1860000,hub:false},
  {id:'ATH',name:'Athens',country:'Greece',lat:37.98,lng:23.73,pop:3150000,hub:false},
  {id:'ZCH',name:'Zurich',country:'Switzerland',lat:47.38,lng:8.54,pop:430000,hub:true},
  // Americas
  {id:'NYC',name:'New York',country:'USA',lat:40.71,lng:-74.01,pop:20140000,hub:true},
  {id:'LAX',name:'Los Angeles',country:'USA',lat:34.05,lng:-118.24,pop:13200000,hub:true},
  {id:'CHI',name:'Chicago',country:'USA',lat:41.88,lng:-87.63,pop:9520000,hub:true},
  {id:'HOU',name:'Houston',country:'USA',lat:29.76,lng:-95.37,pop:7340000,hub:false},
  {id:'MIA',name:'Miami',country:'USA',lat:25.77,lng:-80.19,pop:6200000,hub:true},
  {id:'ATL',name:'Atlanta',country:'USA',lat:33.75,lng:-84.39,pop:6300000,hub:true},
  {id:'SFO',name:'San Francisco',country:'USA',lat:37.77,lng:-122.42,pop:4750000,hub:true},
  {id:'SEA',name:'Seattle',country:'USA',lat:47.61,lng:-122.33,pop:4018000,hub:true},
  {id:'DAL',name:'Dallas',country:'USA',lat:32.78,lng:-96.80,pop:7760000,hub:false},
  {id:'PHX',name:'Phoenix',country:'USA',lat:33.45,lng:-112.07,pop:4946000,hub:false},
  {id:'YTO',name:'Toronto',country:'Canada',lat:43.65,lng:-79.38,pop:6460000,hub:true},
  {id:'YVR',name:'Vancouver',country:'Canada',lat:49.28,lng:-123.12,pop:2600000,hub:true},
  {id:'MEX',name:'Mexico City',country:'Mexico',lat:19.43,lng:-99.13,pop:21700000,hub:true},
  {id:'SAO',name:'São Paulo',country:'Brazil',lat:-23.55,lng:-46.63,pop:22430000,hub:true},
  {id:'RIO',name:'Rio de Janeiro',country:'Brazil',lat:-22.91,lng:-43.17,pop:13635000,hub:false},
  {id:'BOG',name:'Bogotá',country:'Colombia',lat:4.71,lng:-74.07,pop:11300000,hub:false},
  {id:'LIM',name:'Lima',country:'Peru',lat:-12.05,lng:-77.04,pop:11200000,hub:false},
  {id:'BUE',name:'Buenos Aires',country:'Argentina',lat:-34.60,lng:-58.38,pop:15400000,hub:false},
  {id:'SCL',name:'Santiago',country:'Chile',lat:-33.46,lng:-70.65,pop:7400000,hub:false},
  // Africa
  {id:'LAG',name:'Lagos',country:'Nigeria',lat:6.52,lng:3.38,pop:24800000,hub:true},
  {id:'KIN',name:'Kinshasa',country:'DR Congo',lat:-4.32,lng:15.32,pop:17000000,hub:false},
  {id:'JHB',name:'Johannesburg',country:'South Africa',lat:-26.20,lng:28.04,pop:6065000,hub:true},
  {id:'NBO',name:'Nairobi',country:'Kenya',lat:-1.29,lng:36.82,pop:5118000,hub:true},
  {id:'CAI',name:'Cairo',country:'Egypt',lat:30.04,lng:31.24,pop:21750000,hub:true},
  {id:'DAR',name:'Dar es Salaam',country:'Tanzania',lat:-6.79,lng:39.21,pop:7400000,hub:false},
  {id:'ABJ',name:'Abidjan',country:'Ivory Coast',lat:5.36,lng:-4.01,pop:5515000,hub:false},
  {id:'ACC',name:'Accra',country:'Ghana',lat:5.56,lng:-.19,pop:3630000,hub:false},
  {id:'ADD',name:'Addis Ababa',country:'Ethiopia',lat:9.02,lng:38.75,pop:5006000,hub:false},
  {id:'KAN',name:'Kano',country:'Nigeria',lat:12.00,lng:8.52,pop:4103000,hub:false},
  {id:'KHT',name:'Khartoum',country:'Sudan',lat:15.56,lng:32.54,pop:7282000,hub:false},
  // Oceania
  {id:'SYD',name:'Sydney',country:'Australia',lat:-33.87,lng:151.21,pop:5312000,hub:true},
  {id:'MEL',name:'Melbourne',country:'Australia',lat:-37.81,lng:144.96,pop:5078000,hub:false},
  {id:'AKL',name:'Auckland',country:'New Zealand',lat:-36.85,lng:174.76,pop:1657000,hub:false},
];

const BODY_SYSTEMS = [
  {id:'respiratory',name:'Respiratory',color:'#2979ff',icon:'🫁',desc:'Lungs, airways, breathing'},
  {id:'cardiovascular',name:'Cardiovascular',color:'#ff1744',icon:'❤️',desc:'Heart, blood vessels'},
  {id:'nervous',name:'Nervous System',color:'#d500f9',icon:'🧠',desc:'Brain, spinal cord, nerves'},
  {id:'immune',name:'Immune System',color:'#00e676',icon:'🛡️',desc:'White blood cells, antibodies'},
  {id:'digestive',name:'Digestive',color:'#ff6d00',icon:'🫀',desc:'Stomach, intestines, liver'},
  {id:'renal',name:'Renal / Urinary',color:'#00e5ff',icon:'🫘',desc:'Kidneys, bladder'},
  {id:'hepatic',name:'Hepatic',color:'#ffea00',icon:'🍊',desc:'Liver, bile ducts'},
  {id:'musculoskeletal',name:'Musculoskeletal',color:'#69f0ae',icon:'💪',desc:'Muscles, bones, joints'},
  {id:'endocrine',name:'Endocrine',color:'#ff80ab',icon:'⚗️',desc:'Hormones, thyroid, adrenal'},
  {id:'dermal',name:'Dermal',color:'#a5d6a7',icon:'🩹',desc:'Skin, mucous membranes'},
  {id:'ocular',name:'Ocular',color:'#80d8ff',icon:'👁️',desc:'Eyes, tear ducts'},
  {id:'hematologic',name:'Hematologic',color:'#ef9a9a',icon:'🩸',desc:'Blood cells, clotting factors'},
  {id:'lymphatic',name:'Lymphatic',color:'#b39ddb',icon:'🔵',desc:'Lymph nodes, spleen'},
  {id:'reproductive',name:'Reproductive',color:'#f48fb1',icon:'🌸',desc:'Reproductive organs'},
  {id:'ent',name:'ENT',color:'#80cbc4',icon:'👂',desc:'Ear, nose, throat'},
];

const SYMPTOMS = [
  'Fever','High Fever','Chills','Fatigue','Malaise',
  'Cough (dry)','Cough (productive)','Shortness of breath','Chest pain',
  'Headache','Severe headache','Neck stiffness','Photophobia',
  'Confusion','Delirium','Seizures','Coma',
  'Nausea','Vomiting','Diarrhea','Abdominal pain',
  'Loss of appetite','Weight loss',
  'Muscle aches (myalgia)','Joint pain (arthralgia)','Back pain',
  'Runny nose','Sore throat','Loss of smell','Loss of taste',
  'Rash','Hemorrhagic rash','Bruising','Bleeding',
  'Jaundice','Pallor','Cyanosis',
  'Swollen lymph nodes','Conjunctivitis (pink eye)',
  'Skin lesions','Vesicles/blisters','Necrosis',
  'Aggressive behavior','Hypersalivation','Hydrophobia',
  'Paralysis','Tremors','Ataxia',
  'Tachycardia','Bradycardia','Hypotension','Shock',
  'Edema','Ascites','Organomegaly',
  'Urinary changes','Dark urine','Oliguria',
];

const SLIDER_DEFS = {
  transmission: [
    {id:'r0',label:'Basic Reproduction Number (R₀)',min:.1,max:20,step:.1,val:2.5,unit:'',fmt:v=>v.toFixed(1),cls:v=>v<1?'success':v<2?'':v<5?'warn':'danger'},
    {id:'env_survival',label:'Environmental Survival (hours)',min:0,max:720,step:1,val:24,unit:'h',fmt:v=>v+'h'},
    {id:'mutation_rate',label:'Mutation Rate',min:0,max:10,step:.1,val:3,unit:'/10',fmt:v=>v.toFixed(1)+'/10'},
    {id:'zoonotic',label:'Animal Reservoir Risk',min:0,max:10,step:.1,val:5,unit:'/10',fmt:v=>v.toFixed(1)+'/10'},
    {id:'aerosol_range',label:'Transmission Range (meters)',min:.1,max:20,step:.1,val:1.5,unit:'m',fmt:v=>v.toFixed(1)+'m'},
    {id:'infectious_dose',label:'Infectious Dose (particles)',min:1,max:100000,step:1,val:100,unit:'',fmt:v=>v>=1000?Math.round(v/1000)+'K':v+''},
  ],
  timeline: [
    {id:'incubation',label:'Incubation Period (days)',min:.5,max:42,step:.5,val:5,unit:'d',fmt:v=>v+'d'},
    {id:'presymptomatic',label:'Pre-symptomatic Infectious (days)',min:0,max:14,step:.5,val:2,unit:'d',fmt:v=>v+'d'},
    {id:'infectious_period',label:'Total Infectious Period (days)',min:1,max:60,step:.5,val:10,unit:'d',fmt:v=>v+'d'},
    {id:'illness_duration',label:'Illness Duration (days)',min:1,max:90,step:1,val:14,unit:'d',fmt:v=>v+'d'},
    {id:'time_to_death',label:'Time to Death (days from symptom)',min:1,max:60,step:1,val:14,unit:'d',fmt:v=>v+'d'},
  ],
  severity: [
    {id:'ifr',label:'Infection Fatality Rate (%)',min:0,max:100,step:.001,val:1.8,unit:'%',fmt:v=>v.toFixed(3)+'%',cls:v=>v<.1?'':v<1?'warn':'danger'},
    {id:'asymp_rate',label:'Asymptomatic Rate (%)',min:0,max:100,step:1,val:40,unit:'%',fmt:v=>v+'%'},
    {id:'hosp_rate',label:'Hospitalization Rate (%)',min:0,max:100,step:.1,val:5,unit:'%',fmt:v=>v.toFixed(1)+'%'},
    {id:'icu_rate',label:'ICU Rate (%)',min:0,max:100,step:.1,val:1,unit:'%',fmt:v=>v.toFixed(1)+'%'},
    {id:'severity_index',label:'Organ Failure Risk',min:0,max:10,step:.1,val:3,unit:'/10',fmt:v=>v.toFixed(1)+'/10'},
  ],
  immune: [
    {id:'immune_evasion',label:'Immune Evasion Score',min:0,max:10,step:.1,val:3,unit:'/10',fmt:v=>v.toFixed(1)+'/10'},
    {id:'reinfection_risk',label:'Re-infection Risk (%)',min:0,max:100,step:1,val:10,unit:'%',fmt:v=>v+'%'},
    {id:'crossimmunity',label:'Cross-immunity from similar viruses',min:0,max:100,step:1,val:0,unit:'%',fmt:v=>v+'%'},
  ],
  init: [
    {id:'init_immunity',label:'Population Pre-immunity (%)',min:0,max:100,step:.5,val:0,unit:'%',fmt:v=>v+'%'},
    {id:'health_capacity',label:'Hospital Beds per 1,000',min:.1,max:20,step:.1,val:3,unit:'',fmt:v=>v.toFixed(1)},
    {id:'pop_density_mult',label:'Urban Density Multiplier',min:.5,max:3,step:.1,val:1,unit:'×',fmt:v=>v.toFixed(1)+'×'},
  ],
  timing: [
    {id:'response_day',label:'Government responds on day',min:0,max:180,step:1,val:30,unit:'d',fmt:v=>'Day '+v},
    {id:'detect_delay',label:'Detection delay (days)',min:0,max:60,step:1,val:14,unit:'d',fmt:v=>v+'d'},
    {id:'border_close_day',label:'Borders close on day',min:0,max:365,step:1,val:60,unit:'d',fmt:v=>v>300?'Never':'Day '+v},
  ],
  vaccine: [
    {id:'vaccine_day',label:'Vaccine available on day',min:30,max:1095,step:1,val:365,unit:'d',fmt:v=>v+'d'},
    {id:'vaccine_eff',label:'Vaccine Efficacy (%)',min:0,max:100,step:1,val:85,unit:'%',fmt:v=>v+'%'},
    {id:'vaccine_rate',label:'Daily Rollout (%pop/day)',min:.01,max:3,step:.01,val:.3,unit:'%/d',fmt:v=>v.toFixed(2)+'%/d'},
    {id:'antiviral_day',label:'Antiviral treatment on day',min:0,max:730,step:1,val:180,unit:'d',fmt:v=>v+'d'},
    {id:'antiviral_eff',label:'Antiviral Efficacy (%)',min:0,max:100,step:1,val:50,unit:'%',fmt:v=>v+'%'},
  ],
  sim: [
    {id:'sim_days',label:'Simulation Duration (days)',min:30,max:1095,step:1,val:365,unit:'d',fmt:v=>v+'d'},
  ],
};

const RESPONSES = [
  {id:'none',name:'No Response',desc:'No measures taken — business as usual.',trans_mult:1.0,mob_mult:1.0},
  {id:'mild',name:'Mild Measures',desc:'Hand hygiene campaigns, advisories, minor distancing.',trans_mult:.85,mob_mult:.9},
  {id:'moderate',name:'Moderate Lockdown',desc:'School closures, mask mandates, work-from-home, restaurant limits.',trans_mult:.6,mob_mult:.5},
  {id:'strict',name:'Strict Lockdown',desc:'Stay-at-home orders, non-essential business closure, enforced masking.',trans_mult:.35,mob_mult:.2},
  {id:'extreme',name:'Total Quarantine',desc:'Full border closure, military enforcement, complete movement ban.',trans_mult:.15,mob_mult:.05},
];

const PRESETS = {
  flu: {
    name:'Influenza H1N1',pathtype:'rna',route:'airborne',origin:'zoonotic',
    r0:1.4,env_survival:24,mutation_rate:6,zoonotic:7,aerosol_range:2,infectious_dose:1000,
    incubation:2,presymptomatic:1,infectious_period:5,illness_duration:7,time_to_death:14,
    ifr:.1,asymp_rate:33,hosp_rate:1,icu_rate:.2,severity_index:2,
    immune_evasion:4,reinfection_risk:20,crossimmunity:15,
    systems:['respiratory','musculoskeletal','immune','endocrine'],
    symptoms:['Fever','Chills','Cough (dry)','Muscle aches (myalgia)','Fatigue','Headache','Sore throat','Runny nose'],
    neuro:false,immunosupp:false,cytokine:false,antibiotic:false,latent:false,
    response:'mild',response_day:30,vaccine_day:180,vaccine_eff:60,
  },
  covid: {
    name:'COVID-19 (SARS-CoV-2)',pathtype:'rna',route:'aerosol',origin:'zoonotic',
    r0:2.9,env_survival:72,mutation_rate:4,zoonotic:8,aerosol_range:5,infectious_dose:200,
    incubation:5,presymptomatic:2,infectious_period:10,illness_duration:14,time_to_death:21,
    ifr:1.0,asymp_rate:40,hosp_rate:5,icu_rate:1.5,severity_index:4,
    immune_evasion:5,reinfection_risk:30,crossimmunity:0,
    systems:['respiratory','cardiovascular','nervous','immune','renal','hematologic','dermal','ent'],
    symptoms:['Fever','Cough (dry)','Fatigue','Loss of smell','Loss of taste','Shortness of breath','Headache','Muscle aches (myalgia)','Sore throat','Chest pain'],
    neuro:false,immunosupp:false,cytokine:true,antibiotic:false,latent:false,
    response:'moderate',response_day:45,vaccine_day:365,vaccine_eff:85,
  },
  ebola: {
    name:'Ebola Virus Disease',pathtype:'rna',route:'contact',origin:'zoonotic',
    r0:1.8,env_survival:6,mutation_rate:3,zoonotic:9,aerosol_range:.5,infectious_dose:1,
    incubation:8,presymptomatic:0,infectious_period:21,illness_duration:21,time_to_death:14,
    ifr:50,asymp_rate:5,hosp_rate:80,icu_rate:40,severity_index:9,
    immune_evasion:7,reinfection_risk:5,crossimmunity:0,
    systems:['immune','hematologic','hepatic','renal','digestive','dermal','cardiovascular'],
    symptoms:['Fever','High Fever','Fatigue','Muscle aches (myalgia)','Headache','Vomiting','Diarrhea','Hemorrhagic rash','Bleeding','Abdominal pain','Jaundice'],
    neuro:false,immunosupp:true,cytokine:true,antibiotic:false,latent:false,
    response:'strict',response_day:21,vaccine_day:180,vaccine_eff:97,
  },
  measles: {
    name:'Measles Virus',pathtype:'rna',route:'aerosol',origin:'mutation',
    r0:15,env_survival:2,mutation_rate:1,zoonotic:1,aerosol_range:10,infectious_dose:1,
    incubation:12,presymptomatic:4,infectious_period:8,illness_duration:10,time_to_death:30,
    ifr:.2,asymp_rate:5,hosp_rate:10,icu_rate:1,severity_index:3,
    immune_evasion:2,reinfection_risk:1,crossimmunity:0,
    systems:['respiratory','immune','dermal','ocular','nervous','ent'],
    symptoms:['Fever','High Fever','Cough (dry)','Runny nose','Conjunctivitis (pink eye)','Rash','Malaise','Loss of appetite'],
    neuro:false,immunosupp:true,cytokine:false,antibiotic:false,latent:false,
    response:'mild',response_day:60,vaccine_day:90,vaccine_eff:97,
  },
  plague: {
    name:'Yersinia pestis (Plague)',pathtype:'bacteria',route:'vector',origin:'environmental',
    r0:2.5,env_survival:240,mutation_rate:1,zoonotic:9,aerosol_range:1,infectious_dose:100,
    incubation:3,presymptomatic:.5,infectious_period:7,illness_duration:14,time_to_death:7,
    ifr:60,asymp_rate:0,hosp_rate:90,icu_rate:50,severity_index:9,
    immune_evasion:8,reinfection_risk:10,crossimmunity:0,
    systems:['lymphatic','immune','cardiovascular','renal','hematologic','respiratory'],
    symptoms:['Fever','High Fever','Chills','Fatigue','Muscle aches (myalgia)','Swollen lymph nodes','Shock','Cyanosis','Bleeding','Necrosis'],
    neuro:false,immunosupp:true,cytokine:true,antibiotic:false,latent:false,
    response:'strict',response_day:14,vaccine_day:730,vaccine_eff:60,
  },
  nhev: {
    name:'NHEV (Neuro-Hemorrhagic Encephalitis Virus)',pathtype:'rna',route:'bite',origin:'zoonotic',
    r0:1.78,env_survival:12,mutation_rate:2,zoonotic:9,aerosol_range:.3,infectious_dose:1,
    incubation:1.5,presymptomatic:.5,infectious_period:23,illness_duration:28,time_to_death:23,
    ifr:95,asymp_rate:0,hosp_rate:100,icu_rate:100,severity_index:10,
    immune_evasion:9,reinfection_risk:0,crossimmunity:0,
    systems:['nervous','cardiovascular','immune','musculoskeletal','endocrine','hematologic','renal','hepatic','respiratory'],
    symptoms:['High Fever','Aggressive behavior','Hypersalivation','Confusion','Delirium','Seizures','Ataxia','Muscle aches (myalgia)','Tachycardia','Bleeding','Necrosis','Jaundice'],
    neuro:true,immunosupp:true,cytokine:true,antibiotic:false,latent:false,
    response:'strict',response_day:60,vaccine_day:730,vaccine_eff:0,
  },
};

const BIO_STAGES = [
  {
    id:0,name:'Healthy',label:'Uninfected',
    desc:'No infection present. All body systems functioning normally. Immune system is on routine patrol.',
    vitals:{
      'Heart Rate':'65 bpm','Blood Pressure':'120/80 mmHg','Temperature':'98.6°F (37.0°C)',
      'Respiratory Rate':'15/min','O₂ Saturation':'99%','Blood Glucose':'90 mg/dL',
      'WBC Count':'7.0 ×10⁹/L','Consciousness':'Alert & Oriented',
    },
    symptoms:[],
    damage:{Respiratory:0,Cardiovascular:0,'Nervous System':0,'Immune System':0,Digestive:0,Renal:0,Hepatic:0,Hematologic:0},
    labs:{'WBC':'7.0 (Normal)','Neutrophils':'55% (Normal)','Lymphocytes':'35% (Normal)','CRP':'<1 mg/L (Normal)','ALT':'25 U/L (Normal)','Creatinine':'1.0 mg/dL (Normal)','Platelets':'250K/μL (Normal)'},
    systems_status:{Respiratory:'ok',Cardiovascular:'ok','Nervous System':'ok','Immune System':'ok',Digestive:'ok',Renal:'ok',Hepatic:'ok',Hematologic:'ok'},
  },
  {
    id:1,name:'Day 1–3',label:'Early Infection',
    desc:'Pathogen enters host. Replication begins in local tissue. Immune system detects foreign antigens and mounts initial response. Patient may feel normal.',
    vitals:{
      'Heart Rate':'72 bpm','Blood Pressure':'118/78 mmHg','Temperature':'99.1°F (37.3°C)',
      'Respiratory Rate':'16/min','O₂ Saturation':'98%','Blood Glucose':'92 mg/dL',
      'WBC Count':'8.5 ×10⁹/L','Consciousness':'Alert',
    },
    symptoms:['Fatigue','Malaise','Mild headache','Low-grade fever'],
    damage:{Respiratory:2,Cardiovascular:1,'Nervous System':1,'Immune System':5,Digestive:1,Renal:1,Hepatic:2,Hematologic:3},
    labs:{'WBC':'8.5 (↑Mild)','Neutrophils':'65% (↑Mild)','Lymphocytes':'25% (Normal)','CRP':'5 mg/L (↑Mild)','ALT':'30 U/L (Normal)','Creatinine':'1.0 mg/dL (Normal)','Platelets':'240K/μL (Normal)'},
    systems_status:{Respiratory:'ok',Cardiovascular:'ok','Nervous System':'ok','Immune System':'warn',Digestive:'ok',Renal:'ok',Hepatic:'ok',Hematologic:'ok'},
  },
  {
    id:2,name:'Day 3–7',label:'Symptomatic',
    desc:'Viral load increasing rapidly. Immune system in full battle mode. Cytokines flood tissues causing systemic inflammation. Symptoms become prominent.',
    vitals:{
      'Heart Rate':'95 bpm','Blood Pressure':'110/70 mmHg','Temperature':'102.2°F (39.0°C)',
      'Respiratory Rate':'20/min','O₂ Saturation':'96%','Blood Glucose':'115 mg/dL',
      'WBC Count':'12.0 ×10⁹/L','Consciousness':'Alert, impaired',
    },
    symptoms:['Fever (39°C)','Chills','Severe fatigue','Headache','Muscle aches','Cough','Sore throat'],
    damage:{Respiratory:20,Cardiovascular:10,'Nervous System':5,'Immune System':35,Digestive:15,Renal:8,Hepatic:15,Hematologic:15},
    labs:{'WBC':'12.0 (↑↑)','Neutrophils':'80% (↑↑)','Lymphocytes':'12% (↓)','CRP':'45 mg/L (↑↑)','ALT':'55 U/L (↑)','Creatinine':'1.1 mg/dL (Normal)','Platelets':'190K/μL (↓Mild)'},
    systems_status:{Respiratory:'warn',Cardiovascular:'warn','Nervous System':'ok','Immune System':'bad',Digestive:'warn',Renal:'ok',Hepatic:'warn',Hematologic:'warn'},
  },
  {
    id:3,name:'Day 7–14',label:'Peak Illness',
    desc:'Maximum viral burden. Immune response may be causing collateral damage. Lungs, liver, and kidneys under significant stress. Risk of complications rises sharply.',
    vitals:{
      'Heart Rate':'110 bpm','Blood Pressure':'100/65 mmHg','Temperature':'103.8°F (39.9°C)',
      'Respiratory Rate':'26/min','O₂ Saturation':'91%','Blood Glucose':'140 mg/dL (stress)',
      'WBC Count':'15.0 ×10⁹/L','Consciousness':'Confused',
    },
    symptoms:['High fever (40°C)','Severe dyspnea','Chest pain','Hypoxia','Confusion','Severe fatigue','Nausea/vomiting','Loss of appetite'],
    damage:{Respiratory:55,Cardiovascular:35,'Nervous System':25,'Immune System':60,Digestive:35,Renal:30,Hepatic:40,Hematologic:40},
    labs:{'WBC':'15.0 (↑↑↑)','Neutrophils':'88% (↑↑↑)','Lymphocytes':'5% (↓↓)','CRP':'120 mg/L (↑↑↑)','ALT':'180 U/L (↑↑)','Creatinine':'1.8 mg/dL (↑)','Platelets':'110K/μL (↓↓)'},
    systems_status:{Respiratory:'crit',Cardiovascular:'bad','Nervous System':'warn','Immune System':'crit',Digestive:'bad',Renal:'bad',Hepatic:'bad',Hematologic:'crit'},
  },
  {
    id:4,name:'Severe',label:'Severe Disease',
    desc:'Multi-organ involvement. Patient likely hospitalized. Ventilator support may be required. Coagulation cascade disrupted. Risk of septic shock elevated.',
    vitals:{
      'Heart Rate':'130 bpm','Blood Pressure':'85/55 mmHg','Temperature':'104.9°F (40.5°C)',
      'Respiratory Rate':'35/min','O₂ Saturation':'82%','Blood Glucose':'200 mg/dL (stress)',
      'WBC Count':'22.0 ×10⁹/L','Consciousness':'Lethargic / stupor',
    },
    symptoms:['Severe respiratory failure','Cyanosis','Shock','Bleeding (DIC)','Acute kidney injury','Liver failure signs','Delirium','Seizures'],
    damage:{Respiratory:80,Cardiovascular:70,'Nervous System':55,'Immune System':85,Digestive:65,Renal:70,Hepatic:75,Hematologic:80},
    labs:{'WBC':'22.0 (↑↑↑↑)','Neutrophils':'93% (↑↑↑↑)','Lymphocytes':'2% (↓↓↓)','CRP':'280 mg/L (↑↑↑↑)','ALT':'800 U/L (↑↑↑↑)','Creatinine':'4.5 mg/dL (↑↑↑)','Platelets':'40K/μL (↓↓↓↓)'},
    systems_status:{Respiratory:'fail',Cardiovascular:'crit','Nervous System':'crit','Immune System':'fail',Digestive:'crit',Renal:'crit',Hepatic:'crit',Hematologic:'fail'},
  },
  {
    id:5,name:'Critical',label:'Critical / Terminal',
    desc:'Imminent organ failure. Patient on life support. Cytokine storm causing catastrophic tissue destruction. Death probable within 24–72 hours without aggressive intervention.',
    vitals:{
      'Heart Rate':'155 bpm (irregular)','Blood Pressure':'60/40 mmHg (shock)',
      'Temperature':'105.8°F (41.0°C)','Respiratory Rate':'Mechanical (ventilator)',
      'O₂ Saturation':'68%','Blood Glucose':'250 mg/dL (stress hyperglycemia)',
      'WBC Count':'35.0 ×10⁹/L','Consciousness':'Coma',
    },
    symptoms:['Coma','Complete respiratory failure','Circulatory collapse','Multi-organ failure','Uncontrolled bleeding','Profound hypoxia','Brain death signs'],
    damage:{Respiratory:98,Cardiovascular:92,'Nervous System':90,'Immune System':98,Digestive:88,Renal:95,Hepatic:96,Hematologic:98},
    labs:{'WBC':'35.0 (↑↑↑↑↑)','Neutrophils':'98% (↑↑↑↑↑)','Lymphocytes':'0.5% (↓↓↓↓)','CRP':'>500 mg/L (↑↑↑↑↑)','ALT':'>5000 U/L (↑↑↑↑↑)','Creatinine':'>8.0 mg/dL (↑↑↑↑)','Platelets':'<10K/μL (critical)'},
    systems_status:{Respiratory:'fail',Cardiovascular:'fail','Nervous System':'fail','Immune System':'fail',Digestive:'fail',Renal:'fail',Hepatic:'fail',Hematologic:'fail'},
  },
];

const TREATMENTS = [
  {name:'Supportive Care',desc:'IV fluids, oxygen supplementation, fever management.',eff:'Reduces mortality by 10–20% in moderate disease.',always:true},
  {name:'Antiviral Therapy',desc:'Directly inhibits viral replication cycle.',eff:'30–70% reduction in viral load if given early.',always:false,req:'antiviral'},
  {name:'Monoclonal Antibodies',desc:'Engineered antibodies that neutralize pathogen.',eff:'50–80% reduction in progression to severe disease.',always:false,req:'antibody'},
  {name:'Corticosteroids',desc:'Dampens hyperactive immune response / cytokine storm.',eff:'Reduces mortality in severe disease by ~30%.',always:true},
  {name:'ICU / Mechanical Ventilation',desc:'Life support for respiratory failure.',eff:'Keeps patients alive; does not treat underlying disease.',always:false,req:'severe'},
  {name:'Plasma Therapy',desc:'Convalescent plasma from recovered patients.',eff:'Variable; may reduce severity in early stages.',always:false,req:'plasma'},
];
